/**
 * Summary Generator
 * Produces plain-language, accessible summaries from AccessInsight
 * Suitable for audio via SpeechSynthesis
 */

import { AccessInsight, UserProfile, Garment } from "./types.js";

/**
 * Generate a brief verbal summary (for audio)
 */
export function generateAudioSummary(insight: AccessInsight): string {
  const parts: string[] = [];

  // Garment name
  parts.push(`For the ${insight.garment_name}:`);

  // Confidence opener
  const opener = {
    high: "This garment may work very well for you.",
    moderate: "This garment may work, but check a few things first.",
    low: "This garment may not be a good fit for you.",
  }[insight.confidence];
  parts.push(opener);

  // Compatibility points (up to 3)
  if (insight.compatibility.length > 0) {
    parts.push(insight.compatibility.slice(0, 3).join(". "));
  }

  // Risk points (up to 2)
  if (insight.risks.length > 0) {
    parts.push("Things to check: " + insight.risks.slice(0, 2).join(". "));
  }

  // Call to action
  parts.push("Ask the seller the provided questions to confirm this will work for you.");

  return parts.filter((p) => p.length > 0).join(" ");
}

/**
 * Generate detailed markdown summary for display
 */
export function generateMarkdownSummary(
  insight: AccessInsight,
  profile: UserProfile,
  garment: Garment
): string {
  let md = `# Accessibility Review: ${garment.name}\n\n`;

  md += `## Your Profile\n`;
  md += `- **Posture:** ${profile.posture}\n`;
  md += `- **Dexterity:** ${profile.dexterity}\n`;
  if (profile.sensory.length > 0) {
    md += `- **Sensory needs:** ${profile.sensory.join(", ")}\n`;
  }
  if (profile.mobility_aids.length > 0) {
    md += `- **Mobility aids:** ${profile.mobility_aids.join(", ")}\n`;
  }
  if (profile.fit_concerns.length > 0) {
    md += `- **Fit concerns:** ${profile.fit_concerns.join(", ")}\n`;
  }

  md += `\n## Confidence Level\n`;
  const confidenceDescriptions = {
    high: "**High** — This garment appears to align well with your needs based on available information.",
    moderate: "**Moderate** — This garment may work, but some details need clarification from the seller.",
    low: "**Low** — Based on your profile, this garment may not be a good fit. Consider other options.",
  };
  md += `${confidenceDescriptions[insight.confidence]}\n`;

  md += `\n## Compatibility Strengths\n`;
  if (insight.compatibility.length > 0) {
    insight.compatibility.forEach((c) => {
      md += `- ✓ ${c}\n`;
    });
  } else {
    md += `- No strong compatibility markers found. Ask seller questions below.\n`;
  }

  md += `\n## Potential Risks or Concerns\n`;
  if (insight.risks.length > 0) {
    insight.risks.forEach((r) => {
      md += `- ⚠ ${r}\n`;
    });
  } else {
    md += `- No major risks identified based on available information.\n`;
  }

  md += `\n## Questions to Ask the Seller\n`;
  insight.questions_for_seller.forEach((q) => {
    md += `- [ ] ${q}\n`;
  });

  md += `\n## Summary\n`;
  md += `${insight.summary}\n`;

  md += `\n---\n`;
  md += `*Report generated by Aequidrape — Adaptive Fit Assessment Tool*\n`;
  md += `*Information provided is for reference only and does not guarantee fit or comfort.*\n`;

  return md;
}

/**
 * Generate text for email/seller inquiry template
 */
export function generateSellerEmailTemplate(
  insight: AccessInsight,
  profile: UserProfile,
  garment: Garment,
  buyerEmail?: string
): string {
  let email = `Subject: Questions About ${garment.name} — Accessibility & Fit\n\n`;
  email += `Dear Seller,\n\n`;
  email += `I'm interested in ${garment.name} but need to check a few details about accessibility and fit before purchasing.\n\n`;

  email += `My access needs:\n`;
  email += `- Posture: ${profile.posture}\n`;
  email += `- Dexterity level: ${profile.dexterity}\n`;
  if (profile.mobility_aids.length > 0) {
    email += `- Mobility aids: ${profile.mobility_aids.join(", ")}\n`;
  }
  if (profile.sensory.length > 0) {
    email += `- Sensory needs: ${profile.sensory.join(", ")}\n`;
  }

  email += `\nQuestions:\n`;
  insight.questions_for_seller.forEach((q, i) => {
    email += `${i + 1}. ${q}\n`;
  });

  email += `\nThank you,\n`;
  if (buyerEmail) {
    email += `${buyerEmail}\n`;
  }

  return email;
}
